[package]
name = "clonerio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18"
gl = "0.14"
glutin = "0.27"
image = "0.23"
